<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }} — Proyectos inmobiliarios</title>
    <meta name="description" content="Explora proyectos inmobiliarios y consulta terrenos disponibles de {{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}.">
    <meta property="og:title" content="{{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}">
    <meta property="og:description" content="Proyectos y disponibilidad inmobiliaria actualizada.">
    @if($systemSettings['login_background_url'])<meta property="og:image" content="{{ $systemSettings['login_background_url'] }}">@endif
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="premium-public">
<header class="portal-header" data-portal-header>
    <a class="portal-logo" href="#inicio">@if($systemSettings['logo_main_url'])<img src="{{ $systemSettings['logo_main_url'] }}" alt="">@endif<span>{{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}</span></a>
    <nav class="portal-nav" id="portal-nav"><a href="#inicio">Inicio</a><a href="#proyectos">Proyectos</a><a href="#disponibilidad">Disponibilidad</a><a href="#noticias">Noticias</a><a href="#contacto">Contacto</a></nav>
    <form class="desktop-login" method="POST" action="{{ route('login.store') }}">@csrf<label><span>Correo electrónico</span><input name="email" type="email" value="{{ old('email') }}" placeholder="correo@empresa.com" autocomplete="email" required></label><label><span>Contraseña</span><input name="password" type="password" placeholder="Contraseña" autocomplete="current-password" required></label><label class="desktop-remember"><input type="checkbox" name="remember" value="1"> Recordarme</label><button class="btn" type="submit">Ingresar</button></form>
    <button class="btn portal-login-open" type="button" data-login-open>Ingresar</button><button class="portal-menu-toggle" type="button" aria-controls="portal-nav" aria-expanded="false" data-portal-menu><i class="fa-solid fa-bars"></i></button>
</header>

@if($errors->any())<div class="portal-login-error" role="alert">{{ $errors->first() }}</div>@endif
<dialog class="mobile-login" data-login-dialog @if($errors->any()) open @endif><form method="POST" action="{{ route('login.store') }}">@csrf<button class="dialog-close" type="button" data-login-close aria-label="Cerrar"><i class="fa-solid fa-xmark"></i></button><span class="eyebrow">Acceso al CRM</span><h2>Iniciar sesión</h2><label>Correo electrónico<input name="email" type="email" value="{{ old('email') }}" autocomplete="email" required></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><label class="login-remember"><input type="checkbox" name="remember" value="1"> Mantener sesión iniciada</label>@if($errors->any())<div class="errors" role="alert">{{ $errors->first() }}</div>@endif<button class="btn" type="submit">Ingresar al CRM</button></form></dialog>

<main>
    <section id="inicio" class="portal-hero" @if($systemSettings['login_background_url']) style="background-image:linear-gradient(90deg,rgba(15,18,24,.86),rgba(15,18,24,.56) 48%,rgba(15,18,24,.2)),url('{{ $systemSettings['login_background_url'] }}')" @endif>
        <div class="portal-hero-copy"><span class="eyebrow">{{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}</span><h1>Encuentra el espacio<br>para tu próximo proyecto de vida.</h1><p>Explora nuestros proyectos inmobiliarios y consulta la disponibilidad actual de terrenos.</p><div class="actions"><a class="btn" href="#disponibilidad">Consultar disponibilidad</a><a class="btn portal-secondary" href="#proyectos">Ver proyectos</a></div></div>
        <div class="portal-stats"><span><strong>{{ $totals['proyectos'] }}</strong> proyectos</span><span><strong>{{ $totals['disponibles'] }}</strong> disponibles</span><span><strong>{{ $totals['vendidos'] }}</strong> vendidos</span><span><strong>{{ $totals['reservados'] }}</strong> reservados</span></div>
    </section>

    <section id="proyectos" class="portal-section portal-projects-unified"><div class="portal-section-heading"><span class="eyebrow">Proyectos</span><h2>Nuestros proyectos</h2><p>Conoce ubicaciones y disponibilidad con datos actualizados.</p></div><div class="client-project-grid">@forelse($urbanizaciones as $urbanizacion)<x-client.urbanization-card :urbanizacion="$urbanizacion" :whatsapp-phone="$whatsappPhone" context="public" />@empty<x-crm.empty-state title="Próximamente nuevos proyectos" />@endforelse</div></section>

    <section id="disponibilidad" class="portal-section portal-availability"><div><span class="eyebrow">Información pública</span><h2>Consulta disponibilidad</h2><p>Selecciona una urbanización para revisar manzanos, lotes, superficies y estados públicos. Nunca mostramos datos de compradores ni información financiera.</p></div><form method="GET" action="{{ route('disponibilidad.publica') }}"><label>Urbanización<select name="urbanizacion_id" required>@foreach($urbanizaciones as $urbanizacion)<option value="{{ $urbanizacion->id }}">{{ $urbanizacion->nombre }} — {{ $urbanizacion->disponibles_count }} disponibles</option>@endforeach</select></label><button class="btn" type="submit">Explorar lotes</button></form></section>

    <section class="portal-section"><div class="portal-section-heading"><span class="eyebrow">Nuestro compromiso</span><h2>¿Por qué elegir {{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}?</h2></div><div class="portal-benefits"><article><i class="fa-regular fa-map"></i><h3>Disponibilidad actualizada</h3><p>Consulta nuestros terrenos y proyectos desde un solo lugar.</p></article><article><i class="fa-regular fa-comments"></i><h3>Atención personalizada</h3><p>Nuestro equipo puede ayudarte a elegir el terreno adecuado.</p></article><article><i class="fa-regular fa-circle-check"></i><h3>Información clara</h3><p>Conoce características y disponibilidad antes de contactar.</p></article></div></section>

    <section id="noticias" class="portal-section portal-news"><div class="portal-section-heading"><span class="eyebrow">Actualidad</span><h2>Noticias y novedades</h2></div><div class="portal-news-grid">@forelse($noticias as $noticia)<article class="portal-news-card">@if($noticia->imageUrl())<img loading="lazy" src="{{ $noticia->imageUrl() }}" alt="{{ $noticia->titulo }}">@else<div class="portal-news-placeholder"><i class="fa-regular fa-newspaper"></i></div>@endif<div><time>{{ $noticia->fecha_publicacion->format('d/m/Y') }}</time><h3>{{ $noticia->titulo }}</h3><p>{{ $noticia->resumen }}</p><a href="{{ route('public.noticias.show', $noticia->slug) }}">Leer más <i class="fa-solid fa-arrow-right"></i></a></div></article>@empty<div class="portal-empty"><i class="fa-regular fa-newspaper"></i><strong>Próximamente nuevas historias</strong><p>Estamos preparando novedades de nuestros proyectos.</p></div>@endforelse</div></section>

    <section id="contacto" class="portal-contact"><div><span class="eyebrow">Contacto</span><h2>Hablemos de tu próximo terreno</h2><p>Cuéntanos qué proyecto te interesa. No te registraremos como cliente formal hasta que corresponda.</p><ul>@if($systemSettings['whatsapp'])<li><i class="fab fa-whatsapp"></i>{{ $systemSettings['whatsapp'] }}</li>@endif @if($systemSettings['telefono'])<li><i class="fa-solid fa-phone"></i>{{ $systemSettings['telefono'] }}</li>@endif @if($systemSettings['email'])<li><i class="fa-regular fa-envelope"></i>{{ $systemSettings['email'] }}</li>@endif @if($systemSettings['direccion'])<li><i class="fa-solid fa-location-dot"></i>{{ $systemSettings['direccion'] }}</li>@endif</ul>@if($whatsappUrl)<a class="btn whatsapp-button" href="{{ $whatsappUrl }}" target="_blank" rel="noopener"><i class="fab fa-whatsapp"></i> Conversar por WhatsApp</a>@endif</div><form method="POST" action="{{ route('public.contacto.store') }}">@csrf @if(session('public_status'))<div class="alert">{{ session('public_status') }}</div>@endif<label>Nombre<input name="nombre" value="{{ old('nombre') }}" required maxlength="150"></label><label>Celular<input name="celular" value="{{ old('celular') }}" required maxlength="50"></label><label>Correo opcional<input name="email" type="email" value="{{ old('email') }}"></label><label>Proyecto de interés<select name="urbanizacion_id"><option value="">Por definir</option>@foreach($urbanizaciones as $urbanizacion)<option value="{{ $urbanizacion->id }}">{{ $urbanizacion->nombre }}</option>@endforeach</select></label><label class="full">Mensaje<textarea name="mensaje" required maxlength="1500">{{ old('mensaje') }}</textarea></label><button class="btn full" type="submit">Enviar consulta</button></form></section>
</main>
<footer class="portal-footer"><div><strong>{{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}</strong><p>{{ $systemSettings['system_subtitle'] }}</p></div><nav><a href="#proyectos">Proyectos</a><a href="#disponibilidad">Disponibilidad</a><a href="#noticias">Noticias</a><a href="#contacto">Contacto</a></nav><small>© {{ now()->year }} {{ $systemSettings['system_name'] ?: $systemSettings['company_name'] }}</small></footer>
<script src="{{ asset('js/password-toggle.js') }}"></script><script src="{{ asset('js/public-portal.js') }}"></script>
</body></html>
