@extends('layouts.app')
@section('content')
@php $activas=$venta->cuotas->whereIn('estado',['pendiente','parcial','vencida']); $saldo=$activas->sum('saldo_pendiente'); $pagos=$venta->cashMovements->where('tipo','ingreso'); @endphp
<div class="topbar"><h1 class="title">Mi terreno</h1><a class="btn secondary" href="{{ route('clientes.mi-cuenta') }}">Inicio</a></div>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="card"><h2>{{ $venta->lote->manzano->urbanizacion->nombre }} / Mz {{ $venta->lote->manzano->codigo }} / Lote {{ $venta->lote->codigo }}</h2><p>Modalidad: <strong>{{ strtoupper($venta->tipo_operacion) }}</strong></p><p>Precio pactado: $us {{ number_format((float)$venta->precio_final,2) }} · Descuento: $us {{ number_format((float)$venta->descuento,2) }} · Inicial: $us {{ number_format((float)$venta->cuota_inicial,2) }}</p><p class="stat-value">{{ $saldo>0?'Saldo $us '.number_format((float)$saldo,2):'PAGADO' }}</p><div class="actions">@if($saldo>0)<a class="btn" href="{{ route('portal.pagar',$venta) }}">Pagar</a>@endif<a class="btn secondary" href="{{ route('portal.documentos',$venta) }}">Documentos</a></div></div>
<div class="card" style="margin-top:18px"><h2>Plan de cuotas</h2><div class="table-scroll"><table class="table"><thead><tr><th>N.º</th><th>Vencimiento</th><th>Monto</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>@foreach($venta->cuotas as $cuota)<tr><td>{{ $cuota->numero }}</td><td>{{ $cuota->fecha_vencimiento?->format('d/m/Y') }}</td><td>{{ number_format((float)$cuota->monto,2) }}</td><td>{{ number_format((float)$cuota->monto_pagado,2) }}</td><td>{{ number_format((float)$cuota->saldo_pendiente,2) }}</td><td>{{ strtoupper($cuota->estado) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card" style="margin-top:18px"><h2>Historial de pagos</h2><div class="table-scroll"><table class="table"><thead><tr><th>Fecha</th><th>Método</th><th>Referencia</th><th>Monto</th><th>Estado</th><th>Recibo</th></tr></thead><tbody>@foreach($pagos as $pago)<tr><td>{{ $pago->fecha?->format('d/m/Y') }}</td><td>{{ $pago->metodo_pago }}</td><td>{{ $pago->referencia }}</td><td>{{ number_format((float)$pago->monto,2) }}</td><td>{{ strtoupper(\App\Models\CashMovement::ESTADO_LABELS[$pago->estado] ?? $pago->estado) }} @if($pago->estado==='rechazado')<br>{{ $pago->motivo_rechazo }}@endif</td><td>@if($pago->estado==='confirmado')<a href="{{ route('portal.recibo',$pago) }}">Recibo</a>@else—@endif</td></tr>@endforeach</tbody></table></div></div>
@endsection
