@extends('layouts.app')
@section('content')
<x-crm.page-header title="Cobranza" subtitle="Gestiona saldos, vencimientos y pagos de clientes.">
    <a class="btn secondary" href="#pendientes"><i class="fa-regular fa-circle-check"></i> Pagos por verificar ({{ $summary['pendientes'] }})</a>
</x-crm.page-header>
<div class="grid stats quick-summary"><div class="card"><span class="muted">Cobrado hoy</span><div class="stat-value">Bs {{ number_format((float)$summary['total'],2) }}</div></div><div class="card">Efectivo<br><strong>Bs {{ number_format((float)$summary['efectivo'],2) }}</strong></div><div class="card">QR<br><strong>Bs {{ number_format((float)$summary['qr'],2) }}</strong></div><div class="card">Transferencia<br><strong>Bs {{ number_format((float)$summary['transferencia'],2) }}</strong></div><div class="card">Operaciones<br><strong>{{ $summary['operaciones'] }}</strong></div></div>
<form method="GET" action="{{ route('cobranza.index') }}" class="card grid crm-filter-bar">
    <label class="wide">Buscar cliente o deuda<input id="q" name="q" value="{{ $search }}" placeholder="Nombre, CI, teléfono, lote, manzano o venta"></label>
    <label>Estado<select name="estado"><option value="">Todos</option><option value="al_dia" @selected(($filters['estado'] ?? '') === 'al_dia')>Al día</option><option value="por_vencer" @selected(($filters['estado'] ?? '') === 'por_vencer')>Por vencer</option><option value="vencido" @selected(($filters['estado'] ?? '') === 'vencido')>Vencidos</option></select></label>
    <label>Vencimiento desde<input type="date" name="vencimiento_desde" value="{{ $filters['vencimiento_desde'] ?? '' }}"></label>
    <label>Vencimiento hasta<input type="date" name="vencimiento_hasta" value="{{ $filters['vencimiento_hasta'] ?? '' }}"></label>
    <label>Asesor<select name="asesor_id"><option value="">Todos</option>@foreach($asesores as $asesor)<option value="{{ $asesor->id }}" @selected((string) ($filters['asesor_id'] ?? '') === (string) $asesor->id)>{{ $asesor->name }}</option>@endforeach</select></label>
    <div class="actions filter-actions"><button class="btn">Buscar</button><a class="btn secondary" href="{{ route('cobranza.index') }}">Limpiar</a></div>
</form>
@if($search!=='' && $ventas->isEmpty())<div class="card"><x-crm.empty-state title="No encontramos deudas" message="Prueba con otro nombre, documento, teléfono o lote." icon="fa-magnifying-glass" /></div>@endif
<div class="grid quick-debts">@foreach($ventas as $venta)@php
$active=$venta->cuotas->whereIn('estado',['pendiente','parcial','vencida'])->where('saldo_pendiente','>',0)->sortBy(fn($c)=>[match($c->estado){'vencida'=>0,'parcial'=>1,default=>2},$c->fecha_vencimiento?->format('Y-m-d')]);
$balance=$active->sum('saldo_pendiente'); $paid=$venta->cashMovements->where('tipo','ingreso')->where('estado','confirmado')->sum('monto'); $next=$active->first(); $history=$venta->cashMovements->where('tipo','ingreso')->sortByDesc('fecha')->take(10);
$financial=$balance<=0?'PAGADO':($active->where('estado','vencida')->isNotEmpty()?'VENCIDA':($next && $next->fecha_vencimiento?->lte(now()->addDays(3))?'PRÓXIMA':'AL DÍA'));
$initials=collect(explode(' ',$venta->cliente->nombre))->filter()->take(2)->map(fn($word)=>mb_strtoupper(mb_substr($word,0,1)))->join('');
@endphp<article @class(['card','quick-debt','financial-debt-card','overdue'=>$financial==='VENCIDA'])><div class="debt-client"><x-crm.avatar :name="$venta->cliente->nombre" :path="$venta->cliente->foto" size="lg" /><div><h2>{{ $venta->cliente->nombre }}</h2>@if($venta->cliente->documento)<span>CI: {{ $venta->cliente->documento }}</span>@endif @if($venta->cliente->telefono)<span>{{ $venta->cliente->telefono }}</span>@endif</div><span class="debt-status">{{ $financial }}</span></div><div class="debt-property"><strong>{{ $venta->lote->manzano->urbanizacion->nombre }}</strong><span>Mz {{ $venta->lote->manzano->codigo }} · Lote {{ $venta->lote->codigo }} · Venta #{{ $venta->id }}</span></div><div class="debt-balance"><span>Saldo pendiente</span><strong>Bs {{ number_format((float)$balance,2,',','.') }}</strong></div><div class="debt-details"><div><span>Precio pactado</span><strong>Bs {{ number_format((float)$venta->precio_final,2,',','.') }}</strong></div><div><span>Pagado</span><strong>Bs {{ number_format((float)$paid,2,',','.') }}</strong></div><div><span>Próxima cuota</span><strong>{{ $next?'Bs '.number_format((float)$next->saldo_pendiente,2,',','.'):'-' }}</strong></div><div><span>Vencimiento</span><strong>{{ $next?->fecha_vencimiento?->format('d/m/Y')??'-' }}</strong></div></div><div class="payment-progress"><i style="width:{{ (float)$venta->precio_final>0?min(100,round(($paid/(float)$venta->precio_final)*100)):0 }}%"></i></div><div class="actions">@if($balance>0)<button type="button" class="btn collect-open" data-modal="collect-{{ $venta->id }}">Cobrar</button>@endif<a class="btn secondary" href="{{ route('cobranza.estado-cuenta',$venta) }}">Estado de cuenta</a><button type="button" class="btn secondary history-open" data-modal="history-{{ $venta->id }}">Historial</button></div></article>
<dialog id="collect-{{ $venta->id }}" class="quick-modal"><form method="POST" action="{{ route('cobranza.store',$venta) }}" data-preview-url="{{ route('cobranza.preview',$venta) }}" class="collect-form">@csrf<h2>Cobrar — {{ $venta->cliente->nombre }}</h2><p>{{ $venta->lote->manzano->urbanizacion->nombre }} / Mz {{ $venta->lote->manzano->codigo }} / Lote {{ $venta->lote->codigo }} · {{ strtoupper($venta->tipo_operacion) }}</p><p>Saldo total: Bs {{ number_format((float)$balance,2) }} · Vencidas: {{ $active->where('estado','vencida')->count() }}</p><label>Cuota seleccionada<select name="cuota_id">@foreach($active as $cuota)<option value="{{ $cuota->id }}" data-balance="{{ $cuota->saldo_pendiente }}">Cuota {{ $cuota->numero }} — {{ strtoupper($cuota->estado) }} — Bs {{ number_format((float)$cuota->saldo_pendiente,2) }}</option>@endforeach</select></label><label>Monto recibido<input name="monto" type="number" min="0.01" step="0.01" value="{{ $next?->saldo_pendiente }}" required></label><label>Tipo de cobro<select name="tipo_aplicacion"><option value="cuotas">Pago de cuotas</option><option value="amortizacion">Amortizar plazo</option></select></label><label>Método<select name="metodo_pago" class="method"><option value="efectivo">Efectivo</option>@if($instructions['qr'])<option value="QR">QR</option>@endif @if($instructions['cuenta_bancaria'])<option value="transferencia">Transferencia</option>@endif</select></label><div class="remote-fields" hidden><label>Verificación<select name="verificacion"><option value="confirmado">Pago verificado en oficina</option><option value="pendiente_verificacion">Pendiente de verificación</option></select></label><label>Banco<input name="banco"></label><label>Referencia<input name="referencia"></label></div><input type="hidden" name="fecha" value="{{ now()->toDateString() }}"><div class="payment-info">@if($instructions['qr'])<div data-method-info="QR" hidden><img src="{{ $instructions['qr']['url'] }}" alt="QR institucional" style="max-width:180px"><p>{{ $instructions['qr']['nombre'] }}</p></div>@endif @if($instructions['cuenta_bancaria'])<div data-method-info="transferencia" hidden><p>{{ $instructions['cuenta_bancaria']['banco'] }} · {{ $instructions['cuenta_bancaria']['titular'] }} · {{ $instructions['cuenta_bancaria']['numero_cuenta'] }}</p></div>@endif</div><div class="preview-box"></div><div class="actions"><button type="button" class="btn preview-button">Previsualizar</button><button type="submit" class="btn success confirm-button" disabled>Confirmar cobro</button><button type="button" class="btn secondary modal-close">Cerrar</button></div></form></dialog>
<dialog id="history-{{ $venta->id }}" class="quick-modal"><h2>Últimos movimientos</h2>@forelse($history as $movement)<p>{{ $movement->fecha?->format('d/m/Y') }} · Bs {{ number_format((float)$movement->monto,2) }} · {{ $movement->metodo_pago }} · {{ $movement->estado }} @if($movement->estado==='confirmado')<a href="{{ route('pdf.recibo',$movement) }}">Recibo</a>@endif</p>@empty<p>Sin movimientos.</p>@endforelse<a class="btn secondary" href="{{ route('caja.index',['q'=>$venta->cliente->nombre,'lote'=>$venta->lote->codigo]) }}">Ver todo</a> <button type="button" class="btn modal-close">Cerrar</button></dialog>
@endforeach</div>
<div class="pagination-wrap">{{ $ventas->links() }}</div>
<section id="pendientes" class="card"><h2>Pagos por verificar ({{ $pending->count() }})</h2><div class="quick-pending">@forelse($pending as $movement)@php($lot=$movement->venta?->lote ?? $movement->cuota?->venta?->lote)<article><strong>{{ $movement->cliente?->nombre }}</strong><br>{{ $lot?->manzano?->urbanizacion?->nombre }} / {{ $lot?->manzano?->codigo }}-{{ $lot?->codigo }}<br>Bs {{ number_format((float)$movement->monto,2) }} · {{ $movement->metodo_pago }} · {{ $movement->banco }} · {{ $movement->referencia }} · {{ $movement->fecha?->format('d/m/Y') }}<div class="actions"><a class="btn secondary" href="{{ route('caja.show',$movement) }}">Ver</a><form method="POST" action="{{ route('cobranza.confirm',$movement) }}">@csrf<button class="btn success">Confirmar</button></form><form method="POST" action="{{ route('cobranza.reject',$movement) }}"><input type="hidden" name="motivo" value=""><button type="button" class="btn danger reject-button">Rechazar</button>@csrf</form></div></article>@empty<p>No existen pagos pendientes.</p>@endforelse</div></section>
@if($result)<dialog open class="quick-modal"><h2>PAGO REGISTRADO</h2><p><strong>{{ $result->estado==='confirmado'?'CONFIRMADO':'PENDIENTE DE VERIFICACIÓN' }}</strong></p><p>Bs {{ number_format((float)$result->monto,2) }} · {{ $result->metodo_pago }}<br>{{ $result->venta?->lote?->manzano?->urbanizacion?->nombre }} / {{ $result->venta?->lote?->manzano?->codigo }}-{{ $result->venta?->lote?->codigo }}</p>@if($result->estado==='confirmado')<p>Cuotas afectadas: {{ $result->pagoAplicaciones->pluck('cuota.numero')->join(', ') }}<br>Saldo restante: Bs {{ number_format((float)$result->venta->cuotas()->whereIn('estado',['pendiente','parcial','vencida'])->sum('saldo_pendiente'),2) }}<br>Recibo #{{ str_pad((string)$result->id,8,'0',STR_PAD_LEFT) }}</p><a class="btn" href="{{ route('pdf.recibo',$result) }}">Imprimir / descargar PDF</a>@endif<button type="button" class="btn secondary modal-close">Cerrar</button></dialog>@endif
<script>document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.modal).showModal()));document.querySelectorAll('.modal-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('.method').forEach(s=>s.addEventListener('change',()=>{let f=s.closest('form');f.querySelector('.remote-fields').hidden=s.value==='efectivo';f.querySelectorAll('[data-method-info]').forEach(i=>i.hidden=i.dataset.methodInfo!==s.value);}));document.querySelectorAll('.collect-form').forEach(f=>{f.querySelector('[name=cuota_id]').addEventListener('change',e=>f.querySelector('[name=monto]').value=e.target.selectedOptions[0].dataset.balance);f.querySelector('.preview-button').addEventListener('click',async()=>{let body=new FormData(f),box=f.querySelector('.preview-box'),button=f.querySelector('.confirm-button');button.disabled=true;let response=await fetch(f.dataset.previewUrl,{method:'POST',headers:{'X-CSRF-TOKEN':body.get('_token'),'Accept':'application/json'},body});let data=await response.json();if(!response.ok){box.textContent=Object.values(data.errors||{error:data.message}).flat().join(' ');return;}box.innerHTML='<strong>Aplicación estimada</strong><br>'+data.aplicaciones.map(a=>'Cuota '+a.numero+': Bs '+a.monto_aplicado+' → '+a.estado_estimado.toUpperCase()).join('<br>')+'<br>Saldo anterior: Bs '+data.saldo_anterior+'<br>Saldo estimado: Bs '+data.saldo_estimado;button.disabled=false;});});document.querySelectorAll('.reject-button').forEach(b=>b.addEventListener('click',()=>{let reason=prompt('Motivo obligatorio del rechazo');if(reason){b.form.motivo.value=reason;b.form.submit();}}));</script>
@endsection
