@extends('layouts.app')
@section('content')
<div class="topbar"><div><h1 class="title">Usuarios del sistema</h1><p class="muted">Empleados, administradores, asesores y personal interno.</p></div><div class="actions"><a href="{{ route('admin.usuarios.create') }}" class="btn">Nuevo usuario</a><a href="{{ route('admin.usuarios.import') }}" class="btn secondary">Importar</a><a href="{{ route('admin.usuarios.export') }}" class="btn secondary">Exportar</a></div></div>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<form class="card filter-form crm-filter-bar" method="GET"><label class="wide">Buscar<input name="q" value="{{ $filters['search'] }}" placeholder="Nombre o correo"></label><label>Rol<select name="rol"><option value="">Todos</option>@foreach($roles as $rol)<option value="{{ $rol->name }}" @selected($filters['role']===$rol->name)>{{ ucfirst($rol->name) }}</option>@endforeach</select></label><label>Estado<select name="estado"><option value="">Todos</option><option value="activo" @selected($filters['estado']==='activo')>Activo</option><option value="inactivo" @selected($filters['estado']==='inactivo')>Inactivo</option></select></label><div class="filter-actions"><button class="btn">Filtrar</button><a class="btn secondary" href="{{ route('admin.usuarios') }}">Limpiar</a></div></form>
<div class="table-scroll"><table class="table crm-table"><thead><tr><th>Foto</th><th>Nombre</th><th>Email</th><th>Rol</th><th>Estado</th><th>Cambio obligatorio</th><th>Acciones</th></tr></thead><tbody>@forelse($users as $user)<tr><td><x-crm.avatar :name="$user->name" :path="$user->foto" size="sm" /></td><td><strong>{{ $user->name }}</strong></td><td>{{ $user->email }}</td><td>{{ $user->roles->pluck('name')->join(', ') ?: 'Sin rol' }}</td><td><span class="badge {{ $user->estado==='activo'?'activo':'inactivo' }}">● {{ strtoupper($user->estado ?? 'activo') }}</span></td><td>{{ $user->must_change_password?'Sí':'No' }}</td><td class="actions crm-actions"><a href="{{ route('admin.usuarios.edit',$user) }}" class="btn secondary">Editar</a><form method="POST" action="{{ route('admin.usuarios.foto.update',$user) }}" enctype="multipart/form-data" class="inline-upload">@csrf<input type="file" name="foto" accept="image/jpeg,image/png,image/webp" required><button class="btn secondary">Foto</button></form>@if($user->foto)<form method="POST" action="{{ route('admin.usuarios.foto.destroy',$user) }}" onsubmit="return confirm('¿Quitar esta fotografía?')">@csrf @method('DELETE')<button class="btn danger">Quitar foto</button></form>@endif</td></tr>@empty<tr><td colspan="7"><x-crm.empty-state title="No existen usuarios internos para mostrar" /></td></tr>@endforelse</tbody></table></div>
<span class="sr-only">Eliminar</span>
{{ $users->links() }}
@endsection
